org.gradle.jvmargs=-Xmx1G

minecraft_version=1.21.11
yarn_mappings=1.21.11+build.4
loader_version=0.18.2
loom_version=1.14-SNAPSHOT

# Fabric API
fabric_version=0.139.4+1.21.11

modmenu_version=12.0.0
clothconfig_version=16.0.141
rei_version=17.0.790

mod_version = 1.2.1
maven_group = zabi.minecraft.nbttooltip
archives_base_name = nbttooltip